### ISSUE TITLE
Apply for US Trademark?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/intellectual-property#3]
@iteles should we contact http://www.londonip.co.uk/ and ask them to help us apply for a US trademark?

**Comment by iteles** [comment]
We should at least initiate that process and find out how much it will cost us :+1:

**Comment by nelsonic** [comment]
Stoked you're on the case! :+1:

**Comment by iteles** [comment]
This is in progress, the total cost for a one-class trademark application from filing through to registration should be in the region of **£2,000 + VAT** provided that no problems arise.

If no problems arise then we should receive an examination report a few months from filing, and presuming that no objections are raised the **mark should be registered around a year from filing**.

**Comment by nelsonic** [comment]
A **_year**_ from filing...!? :open_mouth:

**Comment by iteles** [comment]
I know _rolls eyes_

**Comment by nelsonic** [comment]
Ok. maybe leave this till we get back to London.
we should check our funds and decide how best to invest them.

**Comment by iteles** [comment]
We really need to finish [_tudo_](https://github.com/dwyl/tudo) so we can snooze this kind of thing to only appear later! :stuck_out_tongue:

**Comment by nelsonic** [comment]
Are you **_volunteering**_ to help finish `Tudo`...?

**Comment by iteles** [comment]
Of _course_. It's pretty much the next priority.

**Comment by ghost** [comment]
Closed in favour of #228
