### ISSUE TITLE
Try to get  .co.uk domain?

### ISSUE THREAD

**Issue by iteles** [dwyl/intellectual-property#4]
It seems that the business behind the .co.uk domain may no longer exist. I think it's worth investigating a little further.

**Comment by nelsonic** [comment]
Should we contact dwyl.co.uk and find out if they are still using the domain?
http://www.dwyl.co.uk/contact.html

If so what should we set as a budget...?

**Comment by iteles** [comment]
We absolutely have to.

Let's prove our business model with an MVP first and then get on this.

**Comment by nelsonic** [comment]
Is "_proving_" the business _before_ contacting them for the domain still the plan? :question:

**Comment by ghost** [comment]
@iteles was this person ever contacted?

**Comment by iteles** [comment]
@markwilliamfirth No!

**Comment by ghost** [comment]
Closed in favour of
https://github.com/dwyl/hq/issues/254
